apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-data-v
spec:
  storageClassName: efs-sc
  volumeMode: Filesystem
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0fa0ab175c1a18ace::fsap-0811678eab20521ab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-data-vc
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
