apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  labels:
    app: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app.kubernetes.io/name: consul
        app: consul
    spec:
      serviceAccountName: dev-sa
      securityContext:
        seccompProfile:
           type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 998
        fsGroup: 998
      volumes:
        - name: consul-data
          persistentVolumeClaim:
            claimName: consul-data-vc
      containers:
        - name: consul
          image: gbnexusrepo.glassbeam.com/glassbeam/consul:1.3
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
                drop:
                - CAP_NET_RAW
                - ALL
                add: ['NET_BIND_SERVICE']
          #command: [ "/bin/bash", "-c", "--" ]
          #args: [ "while true; do sleep 30; done;" ]
          ports:
            - containerPort: 8500
          volumeMounts:
            - name: consul-data
              mountPath: "/home/platform/data"
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "500Mi"
          livenessProbe:
            tcpSocket:
              port: 8500
            initialDelaySeconds: 120
            periodSeconds: 120
          readinessProbe:
            tcpSocket:
              port: 8500
            initialDelaySeconds: 120
            periodSeconds: 120
