apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-h2
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0fa0ab175c1a18ace::fsap-084132593616bd22e
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-h2-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
