apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: h2
spec:
  selector:
    matchLabels:
      app: h2
  serviceName: h2
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: h2
        app: h2
    spec:
      serviceAccountName: dev-sa
      securityContext:
        seccompProfile:
           type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 998
        fsGroup: 998
      volumes:
      - name: h2-data-v
        persistentVolumeClaim:
          claimName: efs-h2-claim
      containers:
      - name: h2
        image: jnkserver.glassbeam.com:8082/glassbeam/centos7-java11-h2:1.4.196
        imagePullPolicy: IfNotPresent
        ports:
        - name: h2-tcp
          containerPort: 9092
        - name: h2-web
          containerPort: 8082 
        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do sleep 30; done;" ]
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
                drop:
                - CAP_NET_RAW
                - ALL
                add: ['NET_BIND_SERVICE']
        volumeMounts:
          - name: h2-data-v
            mountPath: "/home/platform/h2/data"
        resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "500Mi"
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 30
          periodSeconds: 10
